### ISSUE TITLE
Add Blender 4.1 to the image

### ISSUE THREAD

**Issue by agajdosi** [BlenderKit/headless-blender-container#4]
add Blender 4.1
update the patch versions of previous Blenders

**Comment by vilemduha** [comment]
could we possibly automate this? Its really possible people upload also from betas. Or we should prevent this in the addon = if blender versoin is beta, prevent upload?

**Comment by agajdosi** [comment]
@vilemduha To automate this it would be ideal to have an API endpoint, which would give all versions of Blender, whether they are released, or pre-released, and URL to download. Suggested at #3.

Unfortunately Blender provides alphas and released versions on different URLs and it is quite hard to get the versions somehow easily.

**Comment by agajdosi** [comment]
Updated.

**Comment by vilemduha** [comment]
Amazing!
